In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as nb

In [4]:
art = nb.array([22,33,44,55])
print(art)

[22 33 44 55]


In [6]:
ar1 = nb.array([22,33,44,55])
print(ar1)
print(ar1.ndim)

[22 33 44 55]
1


In [9]:
art2 = nb.array([[22,33,44,55,66],[11,32,54,67,23]])
print(art2)
print(art2.ndim)


[[22 33 44 55 66]
 [11 32 54 67 23]]
2
